services:
  - type: web
    name: kikuyu-translation
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: SESSION_COOKIE_SECURE
        value: true
      - key: PYTHONUNBUFFERED
        value: true
      - key: PORT
        value: 5000
    autoDeploy: true