services:
  - type: web
    name: kikuyu-translation
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: SESSION_COOKIE_SECURE
        value: true
      - key: PYTHONUNBUFFERED
        value: true
      - key: PORT
        value: 5000
      - key: OPENROUTER_API_KEY
        sync: false  # Set this manually in Render dashboard
      - key: ADMIN_PASSWORD
        sync: false  # Set this manually in Render dashboard
      - key: DATABASE_URL
        value: sqlite:///instance/kikuyu.db
      - key: MIN_CACHE_SIZE
        value: 10
      - key: PROMPT_BATCH_SIZE
        value: 20
    autoDeploy: true